import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.scss";
import { SpeedInsights } from '@vercel/speed-insights/next';
import { GoogleAnalytics } from '@next/third-parties/google';
import { Inter, Roboto_Mono, Noto_Sans } from 'next/font/google';
import Link from 'next/link'
import clsx from "clsx";
import { usePathname } from "next/navigation";
export const metadata: Metadata = {
  title: "NEXTIO",
  description: "Generated by create next app",
};


const inter = Inter({ subsets: ['latin'], display: 'swap', });
const roboto_mono = Roboto_Mono({ subsets: ['latin'], display: 'swap', });
const noto_sans = Noto_Sans({ subsets: ['latin'], display: 'swap', });

import Header from '@/app/components/Header';
import Nav from '@/app/components/Nav';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="ko">
      <body className={`body ${inter.className} ${roboto_mono.className} ${noto_sans.className} antialiased`}>
        <div className="wrap">
          <Header />
          {children}
          
          <Nav />
        
        </div>
        {process.env.SITE_URL === 'https://nextio.vercel.app/' && <SpeedInsights />}
        <GoogleAnalytics gaId="G-9BBCJ4KC3Z" />
      </body>
    </html>
  );
}
