import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.scss";
import { SpeedInsights } from '@vercel/speed-insights/next';
import { GoogleAnalytics } from '@next/third-parties/google';
import { Inter, Roboto_Mono, Noto_Sans } from 'next/font/google';
import Link from 'next/link'
import clsx from "clsx";
import { usePathname } from "next/navigation";
export const metadata: Metadata = {
  title: "NEXTIO",
  description: "Generated by create next app",
};
export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
  userScalable: false,
  viewportFit:'cover',
  shrinkToFit: false,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
}

const inter = Inter({ subsets: ['latin'], display: 'swap', });
const roboto_mono = Roboto_Mono({ subsets: ['latin'], display: 'swap', });
const noto_sans = Noto_Sans({ subsets: ['latin'], display: 'swap', });

import Header from '@/app/components/Header';
import Nav from '@/app/components/Nav';
import Head from 'next/head'; // Head 컴포넌트 추가
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="ko">
      {/* <Head>
        <script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"token": "6c30b2191cbf4221a2b1d4ce6f3b7530"}'></script>
      </Head> */}
      <body className={`body ${inter.className} ${roboto_mono.className} ${noto_sans.className} antialiased`}>
        <div className="wrap">
          <Header />
          {children}
          
          <Nav />
        
        </div>
        {process.env.NEXT_PUBLIC_SITE_URL === 'https://nextio.vercel.app/' && <SpeedInsights />}
        <GoogleAnalytics gaId="G-9BBCJ4KC3Z" />{/* Cloudflare Web Analytics */}
      </body>
    </html>
  );
}
